import Head from 'next/head'
import Orders from '@/pages/orders/orders'
import Cards from '@/components/Cards/Cards'
import Main from './main'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main/>
    </>
    
  )
}
